name: genshinfan
description: Genshin Fan - Power by Anh Khoa
publish_to: "none"
version: "1.0.1"

environment:
  sdk: ">=3.0.0-63.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get:
  get_storage:

  fluttertoast: ^8.2.1
  flutter_custom_clippers: ^2.0.0
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.13.0
  animate_do: ^3.0.2
  smooth_page_indicator: ^1.1.0
  styled_text: ^7.0.0
  dio: ^5.1.1
  http: ^0.13.5
  archive: ^3.3.7
  connectivity_plus: ^3.0.4
  package_info_plus: ^3.1.0
  path_provider: ^2.0.14
  crypto: ^3.0.2
  url_launcher: ^6.1.10
  flutter_email_sender: ^5.2.0
  in_app_update: ^4.0.1
  collection: ^1.17.2

  data_table_2: ^2.4.2
  dropdown_button2: ^2.1.0
  dropdown_search: ^5.0.6
  multi_select_flutter: ^4.1.3
  flutter_signin_button: ^2.0.0

  firebase_remote_config: ^4.0.1
  firebase_analytics: ^10.1.4
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  firebase_auth: any
  google_sign_in: ^6.1.0
  translator: ^0.1.7

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
