name: genshinfan
description: Genshin Fan - Power by Anh Khoa
publish_to: 'none'
version: "1.0.1"

environment:
  sdk: '>=3.0.0-63.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get:
  get_storage:
  
  fluttertoast: ^8.1.3
  flutter_custom_clippers: ^2.0.0
  cached_network_image: ^3.2.2
  flutter_launcher_icons: ^0.12.0
  animate_do: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  styled_text: ^5.1.0
  dio: ^5.0.0
  http: ^0.13.5
  archive: ^3.3.1
  connectivity_plus: ^3.0.3
  package_info_plus: ^3.0.3 
  path_provider: ^2.0.11
  crypto: ^3.0.2
  url_launcher: ^6.1.10
  flutter_mailer: ^2.0.2
  data_table_2: ^2.3.10
  dropdown_button2: ^1.9.4
  rounded_loading_button: ^2.1.0
  flutter_signin_button: ^2.0.0

  firebase_remote_config: ^3.0.13
  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"