import 'dart:ui';

import 'package:genshinfan/objects/app/language.dart';

// Đức 

const german = Language(
  languageCode: "German",
  language: "Deutsch",
  locale: Locale("de", 'DE'),
);

const Map<String, String> de = {
  "welcome_to_app": "Welcome to Genshin Fan",
  "version": "Version @version",

  "loading": "Wird geladen...",
  "downloading": "@percent% Heruntergeladen",
  "decompressing": "Dekomprimieren...",
  "processing": "Wird bearbeitet",
  "checking": "Überprüfung",
  "no_data_version": "Es gibt keine neue Datenversion",
  "update_new_data": "Neue Daten aktualisieren",
  "complete": "Vollständig!",
  "wait_a_minute": "Warten Sie eine Minute",
  "data_failure": "Daten können nicht geladen werden! Bitte schalten Sie das Netzwerk ein.",
  "not_internet": "Internetverbindung fehlgeschlagen!",
  "setting": "Einstellungen",
  "dark_theme": "Dunkles Thema",
  "change_language": "Sprache ändern",
  "choose_language": "Sprache wählen",
  "character": "Charakter",
  "weapon": "Waffe",
  "teyvat_resource": "Teyvats Ressourcen",
  "food": "Essen",
  "artifact": "Artefakt",
  "domain": "Domain",
  "animal": "Tier",
  "enemy": "Feind",
  "achievement": "Leistung",
  "windglider": "Windgleiter",
  "forging_recipe": "Foring-Rezept",
  "namecard": "Visitenkarte",
  "outfit": "Outfit",
  "choose_character": "Bitte Charakter auswählen",
  "element": "Element",
  "rarity": "Seltenheit",
  "especially": "Besonders",
  "information": "Information",
  "character_information": "Zeicheninformationen",
  "substat": "Substat",
  "gender": "Geschlecht",
  "birthday": "Geburtstag",
  "travelerBirthday": "Geburtstag des Reisenden",
  "affiliation": "Zugehörigkeit",
  "region": "Region",
  "description": "Beschreibung",
  "skill": "Fähigkeit",
  "skill_passive": "Passiv",
  "constellation": "Konstellation",
  "ascension": "Aufstieg",
  "level": "Eben",
  "ascend": "Aufsteigen",
  "resource": "Ressource",
  "skill_ascension": "Skill-Aufstieg",
  "stats": "Statistiken",
  "weapon_information": "Waffeninformationen",
  "talent_stats": "Skill-Statistiken",
  "choose_weapon": "Bitte Waffe auswählen",
  "refinement": "Raffinesse",
  "type": "Typ",
  "story": "Geschichte",
  "effectname": "Effektname",
  "resource_information": "Ressourceninformationen",
  "choose_resource": "Bitte wählen Sie Ressource",
  "dupealias": "Mehr Informationen",
  "source": "Quelle",
  "days_of_week": "Wochentag",
  "artifact_information": "Artefakt-Informationen",
  "choose_artifact": "Bitte wählen Sie Artefakt",
  "set1": "Aktiviere 1 Gegenstand",
  "set2": "2er-Set aktivieren",
  "set4": "4er-Set aktivieren",
  "domain_information": "Domäneninformationen",
  "choose_domain": "Bitte wählen Sie Dungeon",
  "domainentrance": "Eingang",
  "recommendedlevel": "Empfohlenes Niveau",
  "unlockrank": "Rang freischalten",
  "recommendedelements": "Empfohlenes Element",
  "disorder": "Störung",
  "reward": "Belohnen",
  "choose_enemy": "Bitte wählen Sie Feind",
  "enemy_information": "Informationen zum Feind",
  "monster": "Monster",
  "specialname": "Besonderer Name",
  "notification": "Benachrichtigung",
  "notification_change_language":
      "Nachdem Sie die Sprache geändert haben, wird die Anwendung neu gestartet, um Daten in der Sprache Ihrer Wahl zu laden.",
  "cancel": "Stornieren",
  "ok": "Zustimmen",
  "double_click_exit": "Zum Beenden erneut drücken",
  "today": "Heute",
  "birthday_in_month": "Geburtstage des Monats",
  "option": "Möglichkeit",
  "success": "Erfolgreich",
  "not": "Nicht",
  "note": "Notiz",
  "daily_reset_time":
      "<b>Tägliches Zurücksetzen</b> findet alle 04:00 (4 Uhr morgens) statt, basierend auf der Zeitzonenzeit des Servers.\n\n - Server Asien (AS): GMT+8\n - Server Europa (EU): GMT+1\n - Server Amerika (NA): GMT-5",
  "character_up_today": "Charaktere können tagsüber Upgrade-Materialien finden.",
  "weapon_up_today": "Waffen können tagsüber Upgrade-Materialien finden.",
  "genshin_map": "Teyvat Map",
  "notification_open_genshin_map":
      "Möchten Sie <b>Teyvat Map</b> im Browser öffnen?",
  "update": "Aktualisieren",
  "check_update": "Datenaktualisierung prüfen",
  "description_update_setting": "Daten für die Anwendung prüfen und aktualisieren.",
  "contribute": "Beitragen",
  "character_building": "Charakterentwicklung",
  "contribute_translation": "Übersetzungen beisteuern",
  "send_feedback": "Feedback abschicken",
  "description_send_feedback": "E-Mail an den Entwickler.",
  "other": "Andere",
  "join_discord": "Discord-Server beitreten.",
  "confirm": "Bestätigen",
  "access_throughput": "Zugriffsdurchsatz",
  "total": "Gesamt",
  "this_month": "Diesen Monat",
  "set2_artifact": "Set mit 2 Artefakten",
  "set4_artifact": "Set mit 4 Artefakten",
  "sands_effect": "Sand-Effekt",
  "goblet_effect": "Kelch-Effekt",
  "circlet_effect": "Circlet-Effekt",
  "user_information": "Nutzerinformation",
  "login": "Anmeldung",
  "logout_question": "Möchten Sie sich abmelden?",
  "refresh_traffic": "Datenverkehr aktualisieren?",
  "required_login": "Sie müssen sich anmelden, um diese Funktion auszuführen.",
  "admin": "Administrator",
  "admin_description": "Bewerbungsmanagement",
  "user_management": "Benutzerverwaltung",
  "data_management": "Datenmanagement",
  "manager": "Manager",
  "contribution_character": "Beitragscharakter",
  "role_and_data_user": "Benutzerrechte und Daten.",
  "manage_user_character_contribution": "Verwalten Sie den Charakterbeitrag des Benutzers.",
  "choose_full_info": "Sie müssen die Informationen vollständig auswählen.",
  "author": "Autor",
  "invalid": "Ungültig",
  "delete": "Löschen",
  "delete_contribute": "Diesen Benutzerbeitrag löschen?",
  "add_contribute_to_database": "Diesen Beitrag zur Datenbank hinzufügen?",
  "delete_contribute_to_database": "Diesen Beitrag löschen?",
  "contribute_manage_empty": "Noch keine Beiträge",
  "censor": "Zensieren",
  "member": "Mitglied",
  "permission": "Erlaubnis",
  "permission_denied": "Zugriff verweigert",
  "error": "Fehler",
  "note_contribute_character_building":
      "Diese beigetragenen Daten werden von Moderatoren überprüft und genehmigt.",
  "timeout_exception": "Timeout-Ausnahme",
  "reset": "Zurücksetzen",
  "filter_character": "Zeichen filtern",
  "filter_weapon": "Waffe filtern",
  "filter_artifact": "Artefakt filtern",
  "filter_domain": "Filterkerker",
  "filter_resource": "Filtern Sie die Ressourcen von Teyvat",
  "filter_enemy": "Feind filtern",
  "reset_filter_comfirm": "Möchten Sie den Filter zurücksetzen?",
  "sort_name": "Nach Name sortieren",
  "filter_with_rarity": "Filtern Sie nach einer einzelnen Rarität",
  "empty_character": "Keine Zeichen",
  "empty_artifact": "Kein Artefakt",
  "empty_resource": "Keine Teyvat-Ressource",
  "empty_weapon": "Keine Waffe",
  "all": "Alle",
  "online": "Online",

  "note_home":
      "Dies ist eine Beta-Version, eine Testversion von Genshin Fan, bevor sie offiziell veröffentlicht wird. In dieser Version werden neue Funktionen hinzugefügt und Fehler behoben, das Produkt ist jedoch noch unvollständig und kann kleinere Fehler und Probleme aufweisen.\nIhr Beitrag zur Sprachübersetzung in der Beta-Version ist sehr wichtig, um zur Verbesserung der Qualität des Produkts beizutragen. Sie können helfen, indem Sie Feedback zu Begriffen und Sprachstrukturen im Produkt geben. Dies erleichtert die Verwendung des Produkts für Benutzer und erleichtert auch Benutzern in verschiedenen Ländern und Regionen die Verwendung des Produkts. Neben dem Beitrag zur Bewerbungssprache freue ich mich auch auf Ihren Beitrag zum Charakteraufbau. Sie können zu den <b>Einstellungen</b> gehen, um einen Beitrag zu leisten.\nIch freue mich auf Ihren Beitrag, um das Produkt zu verbessern und sicherzustellen, dass es sein volles Potenzial ausschöpft. Ich werde die Beta-Version weiterhin aktualisieren und auf Ihr Feedback hören, um sicherzustellen, dass das Endprodukt Ihren Anforderungen am besten entspricht.",

  // date
  "day1": "Montag",
  "day2": "Dienstag",
  "day3": "Mittwoch",
  "day4": "Donnerstag",
  "day5": "Freitag",
  "day6": "Samstag",
  "day7": "Sonntag",

  // game
  "FIGHT_PROP_ATTACK_PERCENT": "ANG (%)",
  "FIGHT_PROP_ROCK_ADD_HURT": "Geo-SCH-Bonus (%)",
  "FIGHT_PROP_ICE_ADD_HURT": "Kryo-SCH-Bonus (%)",
  "FIGHT_PROP_ELEC_ADD_HURT": "Elektro-SCH-Bonus (%)",
  "FIGHT_PROP_FIRE_ADD_HURT": "Pyro-SCH-Bonus (%)",
  "FIGHT_PROP_WATER_ADD_HURT": "Hydro-SCH-Bonus (%)",
  "FIGHT_PROP_WIND_ADD_HURT": "Anemo-SCH-Bonus (%)",
  "FIGHT_PROP_GRASS_ADD_HURT": "Dendro-SCH-Bonus (%)",
  "FIGHT_PROP_HEAL_ADD": "Heilungsbonus (%)",
  "FIGHT_PROP_DEFENSE_PERCENT": "VTD (%)",
  "FIGHT_PROP_PHYSICAL_ADD_HURT": "Physischer SCH-Bonus (%)",
  "FIGHT_PROP_ELEMENT_MASTERY": "Elementarkunde",
  "FIGHT_PROP_CHARGE_EFFICIENCY": "Aufladerate (%)",
  "FIGHT_PROP_HP_PERCENT": "LP (%)",
  "FIGHT_PROP_CRITICAL": "KT (%)",
  "FIGHT_PROP_CRITICAL_HURT": "KSCH (%)",

  // các loại chỉ số
  "attack": "ANG",
  "hp": "LP",
  "def": "VTD",
  "energy_recharge": "Aufladerate",
  "elemental_mastery": "Elementarkunde",
  "crit_rate": "KT",
  "crit_dame": "KSCH",
  "dame_physical": "Physischer SCH-Bonus",
  "dame_element": "SCH-Bonus",
  "healing_bonus": "Heilungsbonus",

  // element
  "anemo": "Anemo",
  "geo": "Geo",
  "electro": "Elektro",
  "dendro": "Dendro",
  "pyro": "Pyro",
  "hydro": "Hydro",
  "cryo": "Kryo",
  "none": "k. A.",

  "e_anemo": "Anemo",
  "e_geo": "Geo",
  "e_electro": "Elektro",
  "e_dendro": "Dendro",
  "e_pyro": "Pyro",
  "e_hydro": "Hydro",
  "e_cryo": "Kryo",

  // weapon
  "sword": "Einhänder",
  "bow": "Bogen",
  "claymore": "Zweihänder",
  "catalyst": "Katalysator",
  "polearm": "Stangenwaffe",

  // region
   "mondstadt": "Mondstadt",
  "sumeru": "Sumeru",
  "inazuma": "Inazuma",
  "liyue": "Liyue",
  "snezhnaya": "Snezhnaya",
};
