import 'dart:ui';

import '../../models/language.dart';

const english = Language(
  languageCode: "English",
  language: "English",
  code: "en",
  locale: Locale("en"),
);

const Map<String, String> en = {
  "welcome_to_app": "Welcome to Genshin Fan",
  "version": "Version @version",
  "key": "english",
  "language": "English",
  "loading": "Loading...",
  "downloading": "@percent% Downloaded.",
  "decompressing": "Decompressing...",
  "processing": "Processing",
  "checking": "checking",
  "complete": "Complete!",
  "wait_a_minute": "Wait a minute",
  "data_failure": "Unable to load data! Please turn on the network.",
  "not_internet": "Internet connection failed!",
  "setting": "Settings",
  "dark_theme": "Dark theme",
  "change_language": "Change language",
  "choose_language": "Choose language",
  "character": "Character",
  "weapon": "Weapon",
  "teyvat_resource": "Teyvat's Resources",
  "food": "Food",
  "artifact": "Artifact",
  "domain": "Domain",
  "animal": "Animal",
  "enemy": "Enemy",
  "achievement": "Achievement",
  "windglider": "Windglider",
  "forging_recipe": "Foring recipe",
  "namecard": "Name card",
  "outfit": "Outfit",
  "choose_character": "Please choose character",
  "element": "Element",
  "rarity": "Rarity",
  "especially": "Especially",
  "information": "Information",
  "character_information": "Character infomation",
  "substat": "Substat",
  "gender": "Gender",
  "birthday": "Birthday",
  "travelerBirthday": "Traveler's birthday",
  "affiliation": "Affiliation",
  "region": "Region",
  "description": "Description",
  "skill": "Skill",
  "skill_passive": "Passive",
  "constellation": "Constellation",
  "ascension": "Ascension",
  "level": "Level",
  "ascend": "Ascend",
  "resource": "Resource",
  "skill_ascension": "Skill Ascension",
  "stats": "Stats",
  "attack": "Attack",
  "hp": "HP",
  "def": "Defense",
  "weapon_information": "Weapon Information",
  "talent_stats": "Skill stats",
  "choose_weapon": "Please choose Weapon",
  "refinement": "Refinement",
  "type": "Type",
  "story": "Story",
  "effectname": "Effect name",
  "resource_information": "Resource Information",
  "choose_resource": "Please choose Resource",
  "dupealias": "More information",
  "source": "Source",
  "days_of_week": "Day of Week",

  "artifact_information": "Artifact Information",
  "choose_artifact": "Please choose Artifact",
  "set1": "Activate 1 item",
  "set2": "Activate set of 2",
  "set4": "Activate set of 4",

  "domain_information": "Domain Information",
  "choose_domain": "Please choose Dungeon",
  "domainentrance": "Entrance",
  "recommendedlevel": "Recommended level",
  "unlockrank": "Unlock rank",
  "recommendedelements": "Recommended element",
  "disorder": "Disorder",
  "reward": "Reward",
  "choose_enemy": "Please choose Enemy",
  "enemy_information": "Enemy Information",
  "monster": "Monster",
  "specialname": "Special name",
  "notification": "Notification",
  "notification_change_language":
      "After you change the language, the application will restart to load data in the language of your choice.",
  "cancel": "Cancel",
  "ok": "Agree",
  "double_click_exit": "Press again to exit",
  "today": "Today",
  "birthday_in_month": "Birthdays of the month",
  "day1": "Monday",
  "day2": "Tuesday",
  "day3": "Wednesday",
  "day4": "Thursday",
  "day5": "Friday",
  "day6": "Saturday",
  "day7": "Sunday",
  "month1": "January",
  "month2": "February",
  "month3": "March",
  "month4": "April",
  "month5": "May",
  "month6": "June",
  "month7": "July",
  "month8": "August",
  "month9": "September",
  "month10": "October",
  "month11": "November",
  "month12": "December",
  "note": "Note",
  "daily_reset_time":
      "<b>Daily Reset</b> takes place every 04:00 (4AM), based on the server time zone time.\n\n - Server Asia (AS): GMT+8\n - Server Europe (EU): GMT+1\n - Server America (NA): GMT-5",
  "character_up_today": "Characters can find upgrade materials during the day.",
  "weapon_up_today": "Weapons can find upgrade materials during the day.",
  "genshin_map": "Genshin Map",
  "notification_open_genshin_map":
      "Do you want to open <b>Genshin Map</b> in the browser?",
  "update": "Update",
  "check_update": "Check data update.",
  "description_update_setting": "Check and update data for the application.",
  "contribute": "Contribute",
  "contribute_character_building": "Character building",
  "contribute_translation": "Contribute translations",
  "send_feedback": "Send feedback",
  "description_send_feedback": "Email the developer.",
  "other": "Other",
  "join_discord": "Join Discord server.",
  "confirm": "Confirm",
  "access_throughput": "Access throughput",
  "total": "Total",
  "this_month": "This month",
  // game
  // stat character
  "FIGHT_PROP_ATTACK_PERCENT": "Attack (%)",
  "FIGHT_PROP_ROCK_ADD_HURT": "Geo DMG Bonus (%)",
  "FIGHT_PROP_ICE_ADD_HURT": "Cryo DMG Bonus (%)",
  "FIGHT_PROP_ELEC_ADD_HURT": "Electro DMG Bonus (%)",
  "FIGHT_PROP_FIRE_ADD_HURT": "Pyro DMG Bonus (%)",
  "FIGHT_PROP_WATER_ADD_HURT": "Hydro DMG Bonus (%)",
  "FIGHT_PROP_WIND_ADD_HURT": "Anemo DMG Bonus (%)",
  "FIGHT_PROP_GRASS_ADD_HURT": "Dendro DMG Bonus (%)",
  "FIGHT_PROP_HEAL_ADD": "Healing Bonus (%)",
  "FIGHT_PROP_DEFENSE_PERCENT": "DEF (%)",
  "FIGHT_PROP_PHYSICAL_ADD_HURT": "Physical DMG Bonus (%)",
  "FIGHT_PROP_ELEMENT_MASTERY": "Elemental Mastery",
  "FIGHT_PROP_CHARGE_EFFICIENCY": "Energy Recharge (%)",
  "FIGHT_PROP_HP_PERCENT": "HP (%)",
  "FIGHT_PROP_CRITICAL": "CRIT Rate (%)",
  "FIGHT_PROP_CRITICAL_HURT": "CRIT DMG (%)",

  // element
  "anemo": "Anemo",
  "geo": "Geo",
  "electro": "Electro",
  "dendro": "Dendro",
  "pyro": "Pyro",
  "hydro": "Hydro",
  "cryo": "Cryo",
  "none": "None",

  "e_cryo": "Cryo",
  "e_hydro": "Hydro",
  "e_pyro": "Pyro",
  "e_electro": "Electro",
  "e_anemo": "Anemo",
  "e_geo": "Geo",
  "e_dendro": "Dendro",

  // weapon
  "sword": "Sword",
  "bow": "Bow",
  "claymore": "Claymore",
  "catalyst": "Catalyst",
  "polearm": "Polearm",
};
