import 'dart:ui';

import 'package:genshinfan/objects/app/language.dart';

// nga

const russian = Language(
  languageCode: "Russian",
  language: "Тианг Нга",
  locale: Locale("ru", 'RU'),
);

const Map<String, String> ru = {
  "welcome_to_app": "Welcome to Genshin Fan",
  "version": "Version @version",

  "loading": "Загрузка...",
  "downloading": "@percent% загружено.",
  "decompressing": "Распаковка...",
  "processing": "Обработка",
  "checking": "Проверка",
  "no_data_version": "Новой версии данных нет.",
  "update_new_data": "Обновите новые данные.",
  "complete": "Полный!",
  "wait_a_minute": "Подождите минуту",
  "data_failure": "Не удалось загрузить данные! Пожалуйста, включите сеть.",
  "not_internet": "Потеряно соединение",
  "setting": "Настройки",
  "dark_theme": "Тëмная тема",
  "change_language": "Выбрать язык",
  "choose_language": "Выбрать язык",
  "character": "Персонаж",
  "weapon": "Оружие",
  "teyvat_resource": "Ресурсы Тейвата",
  "food": "Еда",
  "artifact": "Артефакт",
  "domain": "Подземелье",
  "animal": "Животные",
  "enemy": "Враги",
  "achievement": "Достижение",
  "windglider": "Ветрокрыл",
  "forging_recipe": "Foring recipe",
  "namecard": "Именная карта",
  "outfit": "Одежда",
  "choose_character": "Пожалуйста выберете персонажа",
  "element": "Элемент",
  "rarity": "Редкость",
  "especially": "Особенно",
  "information": "Информация",
  "character_information": "Информация о персонаже",
  "substat": "Подстат",
  "gender": "Пол",
  "birthday": "День рождения",
  "travelerBirthday": "День рождения путешественника",
  "affiliation": "принадлежность",
  "region": "Регион",
  "description": "Описание",
  "skill": "Навык",
  "skill_passive": "Пасивка",
  "constellation": "Созвездие",
  "ascension": "Вознесение",
  "level": "Уровень",
  "ascend": "Восхождение",
  "resource": "Ресурс",
  "skill_ascension": "Вознесение навыков",
  "stats": "Статы",
  "weapon_information": "Информация о оружии",
  "talent_stats": "Статы навыка",
  "choose_weapon": "Пожалуйста выберете оружие",
  "refinement": "Уточнение",
  "type": "Тип",
  "story": "История",
  "effectname": "Имя эффекта",
  "resource_information": "Информация о ресурсах",
  "choose_resource": "Пожалуйста, выберите Ресурс",
  "dupealias": "Больше информации",
  "source": "Источник",
  "days_of_week": "День недели",
  "artifact_information": "Информация о артефакте",
  "choose_artifact": "Пожалуйста выберете артефакты",
  "set1": "Активировать 1 предмет",
  "set2": "Активировать набор из 2",
  "set4": "Активировать набор из 4",
  "domain_information": "Информация о подземелье",
  "choose_domain": "Пожалуйста выберете подземелье",
  "domainentrance": "Вход",
  "recommendedlevel": "Рекомендуемый ранг",
  "unlockrank": "Разблокировать ранг",
  "recommendedelements": "Рекомендуемые элементы",
  "disorder": "расстройство",
  "reward": "Награда",
  "choose_enemy": "Пожалуйста выберете врага",
  "enemy_information": "Информация о враге",
  "monster": "Монстер",
  "specialname": "Специальное имя",
  "notification": "Уведомление",
  "notification_change_language":
      "После того, как вы измените язык, приложение перезапустится для загрузки данных на выбранном вами языке.",
  "cancel": "Отмега",
  "ok": "Принять",
  "double_click_exit": "Нажмите еще раз, чтобы выйти",
  "today": "Сегодня",
  "birthday_in_month": "Дни рождения в месяце",
  "option": "Настройки",
  "success": "Успешно",
  "not": "Нет",
  "note": "Примечание",
  "daily_reset_time":
      "<b>Ежедневный сброс</b> происходит каждые 04:00 (4:00) в зависимости от часового пояса сервера.\n\n - Сервер Азии (AS): GMT+8\n - Сервер Европа (ЕС): GMT+1\n – Сервер Америка (Северная Америка): GMT-5",
  "character_up_today":
      "Персонажи могут найти материалы для улучшения в течение дня.",
  "weapon_up_today":
      "Оружие может найти материалы для улучшения в течение дня.",
  "genshin_map": "Карта геншина",
  "notification_open_genshin_map":
      "Хотите открыть <b>Genshin Map</b> в браузере?",
  "update": "Обновление",
  "check_update": "Проверить обновление данных.",
  "description_update_setting": "Проверьте и обновите данные для приложения.",
  "contribute": "Способствовать",
  "character_building": "Билдостроение",
  "contribute_translation": "Добавить переводы",
  "send_feedback": "Отправить отзыв",
  "description_send_feedback": "Пишите разработчику.",
  "other": "Другое",
  "join_discord": "Присоединяйтесь к дискорд серверу.",
  "confirm": "Принять",
  "access_throughput": "Пропускная способность доступа",
  "total": "Всего",
  "this_month": "Этот месяц",
  "set2_artifact": "Набор из 2 артефактов",
  "set4_artifact": "Набор из 4 артефактов",
  "sands_effect": "Эффект песка",
  "goblet_effect": "Эффект кубка",
  "circlet_effect": "Эффект обруча",
  "user_information": "Информация о пользователе",
  "login": "Авторизоваться",
  "logout_question": "Вы хотите выйти?",
  "refresh_traffic": "Обновить трафик?",
  "required_login": "Для выполнения этой функции необходимо войти в систему.",
  "admin": "Админ",
  "admin_description": "Управление приложением",
  "user_management": "Управление пользователями",
  "data_management": "Управление данными",
  "manager": "Менеджер",
  "contribution_character": "Вклад Характер",
  "role_and_data_user": "Права пользователя и данные.",
  "manage_user_character_contribution":
      "Управляйте вкладом персонажа пользователя.",
  "choose_full_info": "Вы должны выбрать полную информацию.",
  "author": "Автор",
  "invalid": "Неверный",
  "delete": "Удалить",
  "delete_contribute": "Удалить этот пользовательский вклад?",
  "add_contribute_to_database": "Добавить этот вклад в базу данных?",
  "delete_contribute_to_database": "Удалить этот вклад?",
  "contribute_manage_empty": "Пока нет вкладов",
  "censor": "Цензор",
  "member": "Член",
  "permission": "Разрешение",
  "permission_denied": "Доступ запрещен",
  "error": "Ошибка",
  "note_contribute_character_building":
      "Эти предоставленные данные будут рассмотрены и одобрены модераторами.",
  "timeout_exception": "Исключение тайм-аута",
  "reset": "Перезагрузить",
  "filter_character": "Символ фильтра",
  "filter_weapon": "Фильтровать оружие",
  "filter_artifact": "Артефакт фильтра",
  "filter_domain": "Подземелье фильтров",
  "filter_resource": "Фильтровать ресурсы Тейвата",
  "filter_enemy": "Фильтр врага",
  "reset_filter_comfirm": "Вы хотите сбросить фильтр?",
  "sort_name": "Сортировка по имени",
  "filter_with_rarity": "Фильтр по редкости",
  "empty_character": "Нет персонажей",
  "empty_artifact": "Нет артефактов",
  "empty_resource": "Нет ресурса Тейвата",
  "empty_weapon": "Нет оружия",
  "all": "Всë",
  "online": "В сети",

  "note_home":
      "Это бета-версия, тестовая версия Genshin Fan перед официальным выпуском. В этой версии добавлены новые функции и исправлены ошибки, однако продукт все еще не завершен и может столкнуться с незначительными ошибками и проблемами.\nВаш вклад в языковой перевод в бета-версии очень важен для улучшения качества продукта. Вы можете помочь, предоставив отзыв о терминах и языковых структурах в продукте. Это упрощает использование продукта пользователями, а также упрощает его использование пользователями в разных странах и регионах. Помимо вклада в язык приложения, я также с нетерпением жду вашего вклада в то, как создать персонажа. Чтобы внести свой вклад, перейдите в <b>Настройки</b>.\nЯ с нетерпением жду ваших отзывов, чтобы улучшить продукт и убедиться, что он используется в полной мере. Я буду продолжать обновлять бета-версию и прислушиваться к вашим отзывам, чтобы убедиться, что конечный продукт наилучшим образом соответствует вашим потребностям.",

  // date
  "day1": "Понедельник",
  "day2": "Вторник",
  "day3": "Среда",
  "day4": "Четверг",
  "day5": "Пятница",
  "day6": "Суббота",
  "day7": "Воскресенье",
  // các loại chỉ số
  "attack": "Сила атаки",
  "hp": "HP",
  "def": "Защита",
  "energy_recharge": "Восст. энергии",
  "elemental_mastery": "Мастерство стихий",
  "crit_rate": "Шанс крит. попадания",
  "crit_dame": "Крит. урон",
  "dame_physical": "физ. урона",
  "dame_element": "Элемент урона",
  "healing_bonus": "Бонус лечения",

  // element
  "anemo": "Анемо",
  "geo": "Гео",
  "electro": "Электро",
  "dendro": "Дендро",
  "pyro": "Пиро",
  "hydro": "Гидро",
  "cryo": "Крио",
  "none": "Нет",

  "e_anemo": "Анемо",
  "e_geo": "Гео",
  "e_electro": "Электро",
  "e_dendro": "Дендро",
  "e_pyro": "Пиро",
  "e_hydro": "Гидро",
  "e_cryo": "Крио",

  // weapon
  "sword": "Одноручное",
  "bow": "Стрелковое",
  "claymore": "Двуручное",
  "catalyst": "Катализатор",
  "polearm": "Древковое",

  // region
  "mondstadt": "Мондштадт",
  "sumeru": "Сумеру",
  "inazuma": "Инадзума",
  "liyue": "Ли Юэ",
  "snezhnaya": "Снежная",
};
