import 'dart:ui';

import 'package:genshinfan/objects/app/language.dart';

const chineseTraditional = Language(
  languageCode: "ChineseTraditional",
  language: "中國傳統的",
  locale: Locale("zh", "TW"),
);

const Map<String, String> zhTW = {
  "welcome_to_app": "Welcome to Genshin Fan (ChineseTraditional)",
  "version": "Version @version",
  "key": "english",
  "language": "English",
  "loading": "Loading...",
  "downloading": "@percent% Downloaded.",
  "decompressing": "Decompressing...",
  "processing": "Processing",
  "checking": "Checking",
  "no_data_version": "There is no new data version.",
  "update_new_data": "Update new data.",
  "complete": "Complete!",
  "wait_a_minute": "Wait a minute",
  "data_failure": "Unable to load data! Please turn on the network.",
  "not_internet": "Internet connection failed!",
  "setting": "Settings",
  "dark_theme": "Dark theme",
  "change_language": "Change language",
  "choose_language": "Choose language",
  "character": "Character",
  "weapon": "Weapon",
  "teyvat_resource": "Teyvat's Resources",
  "food": "Food",
  "artifact": "Artifact",
  "domain": "Domain",
  "animal": "Animal",
  "enemy": "Enemy",
  "achievement": "Achievement",
  "windglider": "Windglider",
  "forging_recipe": "Foring recipe",
  "namecard": "Name card",
  "outfit": "Outfit",
  "choose_character": "Please choose character",
  "element": "Element",
  "rarity": "Rarity",
  "especially": "Especially",
  "information": "Information",
  "character_information": "Character infomation",
  "substat": "Substat",
  "gender": "Gender",
  "birthday": "Birthday",
  "travelerBirthday": "Traveler's birthday",
  "affiliation": "Affiliation",
  "region": "Region",
  "description": "Description",
  "skill": "Skill",
  "skill_passive": "Passive",
  "constellation": "Constellation",
  "ascension": "Ascension",
  "level": "Level",
  "ascend": "Ascend",
  "resource": "Resource",
  "skill_ascension": "Skill Ascension",
  "stats": "Stats",
  "weapon_information": "Weapon Information",
  "talent_stats": "Skill stats",
  "choose_weapon": "Please choose Weapon",
  "refinement": "Refinement",
  "type": "Type",
  "story": "Story",
  "effectname": "Effect name",
  "resource_information": "Resource Information",
  "choose_resource": "Please choose Resource",
  "dupealias": "More information",
  "source": "Source",
  "days_of_week": "Day of Week",

  "artifact_information": "Artifact Information",
  "choose_artifact": "Please choose Artifact",
  "set1": "Activate 1 item",
  "set2": "Activate set of 2",
  "set4": "Activate set of 4",

  "domain_information": "Domain Information",
  "choose_domain": "Please choose Dungeon",
  "domainentrance": "Entrance",
  "recommendedlevel": "Recommended level",
  "unlockrank": "Unlock rank",
  "recommendedelements": "Recommended element",
  "disorder": "Disorder",
  "reward": "Reward",
  "choose_enemy": "Please choose Enemy",
  "enemy_information": "Enemy Information",
  "monster": "Monster",
  "specialname": "Special name",
  "notification": "Notification",
  "notification_change_language":
      "After you change the language, the application will restart to load data in the language of your choice.",
  "cancel": "Cancel",
  "ok": "Agree",
  "double_click_exit": "Press again to exit",
  "today": "Today",
  "birthday_in_month": "Birthdays of the month",
  "option": "Option",
  "success": "Successfully",
  "not": "Not",
  "note": "Note",
  "daily_reset_time":
      "<b>Daily Reset</b> takes place every 04:00 (4AM), based on the server time zone time.\n\n - Server Asia (AS): GMT+8\n - Server Europe (EU): GMT+1\n - Server America (NA): GMT-5",
  "character_up_today": "Characters can find upgrade materials during the day.",
  "weapon_up_today": "Weapons can find upgrade materials during the day.",
  "genshin_map": "Genshin Map",
  "notification_open_genshin_map":
      "Do you want to open <b>Genshin Map</b> in the browser?",
  "update": "Update",
  "check_update": "Check data update.",
  "description_update_setting": "Check and update data for the application.",
  "contribute": "Contribute",
  "character_building": "Character building",
  "contribute_translation": "Contribute translations",
  "send_feedback": "Send feedback",
  "description_send_feedback": "Email the developer.",
  "other": "Other",
  "join_discord": "Join Discord server.",
  "confirm": "Confirm",
  "access_throughput": "Access throughput",
  "total": "Total",
  "this_month": "This month",
  "set2_artifact": "Set of 2 artifact",
  "set4_artifact": "Set of 4 artifact",
  "sands_effect": "Sands effect",
  "goblet_effect": "Goblet effect",
  "circlet_effect": "Circlet effect",
  "user_information": "User information",
  "login": "Login",
  "logout_question": "Do you want to sign out?",
  "refresh_traffic": "Refresh traffic?",
  "required_login": "You need to login to perform this function.",
  "admin": "Admin",
  "admin_description": "Application management",
  "user_management": "User management",
  "data_management": "Data management",
  "manager": "Manager",
  "contribution_character": "Contribution Character",
  "role_and_data_user": "User rights and data.",
  "manage_user_character_contribution": "Manage user's Character contribution.",
  "choose_full_info": "You must select full the information.",
  "author": "Author",
  "invalid": "Invalid",
  "delete": "Delete",
  "delete_contribute": "Delete this user contribution?",
  "add_contribute_to_database": "Add this contribution to the database?",
  "delete_contribute_to_database": "Delete this contribution?",
  "contribute_manage_empty": "No contributions yet",
  "censor": "Censor",
  "member": "Member",
  "permission": "Permission",
  "permission_denied": "Permission denied",
  "error": "Error",
  "note_contribute_character_building":
      "This contributed data will be reviewed and approved by moderators.",
  "timeout_exception": "Timeout exception",
  "reset": "Reset",
  "filter_character": "Filter Character",
  "filter_weapon": "Filter Weapon",
  "filter_artifact": "Filter Artifact",
  "filter_domain": "Filter Dungeon",
  "filter_resource": "Filter Teyvat's Resources",
  "filter_enemy": "Filter Enemy",
  "reset_filter_comfirm": "Do you want to reset the filter?",
  "sort_name": "Sort by name",
  "filter_with_rarity": "Filter by a single rarity",
  "empty_character": "No characters",
  "empty_artifact": "No Artifact",
  "empty_resource": "No Teyvat's Resource",
  "empty_weapon": "No Weapon",
  "all": "All",

  "note_home":
      "這是 Beta 版本，是 Genshin Fan 正式發布前的測試版本。 在這個版本中，增加了新功能並修復了錯誤，但是產品仍然不完整，可能會遇到一些小錯誤和問題。\n您在 Beta 版本中對語言翻譯的貢獻對於幫助提高產品質量非常重要。 您可以通過提供有關產品中的術語和語言結構的反饋來提供幫助。 這使得產品更易於用戶使用，也使不同國家和地區的用戶更容易使用該產品。 除了應用語言的貢獻，我也期待你在如何構建角色方面的貢獻。 您可以前往<b>設置</b>進行貢獻。\n我期待收到您的意見以改進產品並確保其發揮最大潛力。 我會繼續更新 Beta 版本並聽取您的反饋，以確保最終產品能夠最好地滿足您的需求。",

  // date
  "day1": "週一",
  "day2": "週二",
  "day3": "週三",
  "day4": "週四",
  "day5": "週五",
  "day6": "週六",
  "day7": "週日",
  "month1": "January",
  "month2": "February",
  "month3": "March",
  "month4": "April",
  "month5": "May",
  "month6": "June",
  "month7": "July",
  "month8": "August",
  "month9": "September",
  "month10": "October",
  "month11": "November",
  "month12": "December",

  // game
  "FIGHT_PROP_ATTACK_PERCENT": "攻擊力 (%)",
  "FIGHT_PROP_ROCK_ADD_HURT": "岩元素傷害加成 (%)",
  "FIGHT_PROP_ICE_ADD_HURT": "冰元素傷害加成 (%)",
  "FIGHT_PROP_ELEC_ADD_HURT": "雷元素傷害加成 (%)",
  "FIGHT_PROP_FIRE_ADD_HURT": "火元素傷害加成 (%)",
  "FIGHT_PROP_WATER_ADD_HURT": "水元素傷害加成 (%)",
  "FIGHT_PROP_WIND_ADD_HURT": "風元素傷害加成 (%)",
  "FIGHT_PROP_GRASS_ADD_HURT": "草元素傷害加成 (%)",
  "FIGHT_PROP_HEAL_ADD": "治療加成 (%)",
  "FIGHT_PROP_DEFENSE_PERCENT": "防禦力 (%)",
  "FIGHT_PROP_PHYSICAL_ADD_HURT": "物理傷害加成 (%)",
  "FIGHT_PROP_ELEMENT_MASTERY": "元素精通",
  "FIGHT_PROP_CHARGE_EFFICIENCY": "元素充能效率 (%)",
  "FIGHT_PROP_HP_PERCENT": "生命值 (%)",
  "FIGHT_PROP_CRITICAL": "暴擊率 (%)",
  "FIGHT_PROP_CRITICAL_HURT": "暴擊傷害 (%)",

  // các loại chỉ số
  "attack": "攻擊力",
  "hp": "生命值",
  "def": "防禦力",
  "elemental_mastery": "元素精通",
  "energy_recharge": "元素充能效率",
  "crit_rate": "暴擊率",
  "crit_dame": "暴擊傷害",
  "dame_physical": "物理傷害加成",
  "dame_element": "元素傷害加成",
  "healing_bonus": "治療加成",

  // element
  "anemo": "風元素",
  "geo": "岩元素",
  "electro": "雷元素",
  "dendro": "草元素",
  "pyro": "火元素",
  "hydro": "水元素",
  "cryo": "冰元素",
  "none": "None",

  "e_anemo": "風元素",
  "e_geo": "岩元素",
  "e_electro": "雷元素",
  "e_dendro": "草元素",
  "e_pyro": "火元素",
  "e_hydro": "水元素",
  "e_cryo": "冰元素",

  // weapon
  "sword": "單手劍",
  "bow": "弓",
  "claymore": "雙手劍",
  "catalyst": "法器",
  "polearm": "長柄武器",

  // region
  "mondstadt": "蒙德",
  "liyue": "璃月",
  "inazuma": "稻妻",
  "sumeru": "須彌",
};
